sudo: required
language: python
dist: trusty  # wily
python:
    - "2.7"
    - "3.5"
    - "3.5-dev" # 3.5 development branch
    - "nightly" # currently points to 3.6-dev
    - "pypy"
branches:
    only:
        - master
        - develop
os:
  - linux
matrix:
  allow_failures:
      - python: "3.5-dev"
      - python: "nightly"


# Install system dependencies
before_install:
  # glfw-cffi requires a working X11 display to run any tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

  # Update System
  - sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ wily main restricted universe multiverse'
  - sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ wily-updates main restricted universe multiverse'
  - sudo apt-get update -qq

  # Install dependencies
  - sudo apt-get install -qq cmake g++-4.8 gcc-4.8 libglew-dev libfreetype6-dev libxrandr-dev libxrandr-dev libxinerama-dev libxcursor-dev freeglut3-dev libxxf86vm-dev

  # Install GLFW 3.1.2
  - wget -O glfw-3.1.2.zip https://github.com/glfw/glfw/releases/download/3.1.2/glfw-3.1.2.zip
  - unzip glfw-3.1.2.zip
  - cd glfw-3.1.2
  - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu
  - make
  - sudo make install
  - cd ..

  # Install special pypy numpy for pypy compatibility or grab standard
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then travis_retry pip install git+https://bitbucket.org/pypy/numpy.git@pypy-4.0.1; fi
  - pip install -r requirements.txt

# Runs first
install:
   - pip install .

# command to run tests
script:
   # - echo 'No tests will run on travis.ci currently'
   - py.test
