sudo: required
language: python
dist: trusty  # wily
python:
    - "pypy"
    - "2.7"
    - "3.5"
    - "3.6"
    - "nightly" # currently points to 3.7-dev

branches:
    only:
        - master
        - develop
os:
  - linux

env:
  global:
    - WORKON_HOME=$HOME/.local/envs
    - GLFW_VERSION=3.2.1
    - GLFW_LIBRARY=/opt/glfw
    - DISPLAY=:99.0
    - GLFW_LIBRARY=$HOME/lib/libglfw.so

matrix:
  fast_finish: true
  allow_failures:
      - python: "nightly"

addons:
  apt:
    packages:
      - [libegl1-mesa, cmake, xorg-dev, libglu1-mesa-dev, mercurial,
         libdbus-1-dev, libgl1-mesa-dev, libglu1-mesa-dev, libpulse-dev,
         libx11-dev, libxcursor-dev, libxext-dev, libxi-dev, libxinerama-dev,
         libxrandr-dev, libxss-dev, libxt-dev, libxv-dev, libxxf86vm-dev,
         libasound2-dev, libts-dev, libudev-dev]


# Install system dependencies
before_install:
  # Update System
  - mkdir -p $HOME/.local/envs
  - sudo apt-get update -qq
  - sudo apt-get install -qq software-properties-common lsb-release wget unzip
  - "export RELEASE_NAME=$(lsb_release -cs)"
  - echo $RELEASE_NAME
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ $RELEASE_NAME main restricted universe multiverse"
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ $RELEASE_NAME-updates main restricted universe multiverse"
  - sudo apt-get update -qq

  # Install dependencies
  - sudo apt-get install -qq cmake g++ gcc xvfb libglew-dev libfreetype6-dev libxrandr-dev libxrandr-dev libxinerama-dev libxcursor-dev freeglut3-dev libxxf86vm-dev libglu1-mesa-dev libegl1-mesa xorg-dev libdbus-1-dev libgl1-mesa-dev libglu1-mesa-dev libpulse-dev libx11-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxrandr-dev libpulse-dev libxss-dev libxt-dev libxv-dev libxxf86vm-dev libasound2-dev libudev-dev

  # Install GLFW $GLFW_VERSION
  - wget -O glfw.zip https://github.com/glfw/glfw/releases/download/$GLFW_VERSION/glfw-$GLFW_VERSION.zip
  - unzip glfw.zip
  - cd glfw-$GLFW_VERSION
  - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=$HOME
  - make
  - sudo make install
  - "export GLFW_LIBRARY=${HOME}/lib/libglfw.so"
  - cd ..

  # Install special pypy numpy for pypy compatibility or grab standard
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then travis_retry pip install git+https://bitbucket.org/pypy/numpy.git@pypy-4.0.1; fi

install:
  - pip install -e .[tests]
  - pip install circus
  # - pip install tox-travis

# command to run tests
script:
   # Run each separately so we have an idea of what's broken in travis
  # glfw-cffi requires a working X11 display to run any tests
  - circusd circus.ini --daemon
  - circusctl list
  - circusctl status xvfb
  - circusctl stats xvfb
  - python -c 'import glfw; print("glfw_initialized == {}".format(glfw.init() == glfw.gl.TRUE))'
  - py.test

after_success:
   - coveralls
