sudo: required
language: python
cache: pip
dist: trusty  # wily
python:
    - "2.7"
    - "3.6"

branches:
    only:
        - master
        - develop
os:
  - linux

env:
  global:
    - WORKON_HOME=$HOME/.local/envs
    - GLFW_LIBRARY=/opt/glfw
    - DISPLAY=:99.0
    - GLFW_LIBRARY=$HOME/lib/libglfw.so
  matrix:
    - GLFW_VERSION=3.2.1
    - GLFW_VERSION=3.2
    - GLFW_VERSION=3.1.2
    - GLFW_VERSION=3.1.1
    - GLFW_VERSION=3.1

addons:
  apt:
    packages:
      - &common_packages [
          'software-properties-common', 'lsb-release', 'wget', 'unzip']
      - &build_packages ['cmake', 'mercurial', ]
      - &sound_packages ['libpulse-dev', 'libasound2-dev']
      - &mesa_packages [
          'libegl1-mesa', 'libglu1-mesa-dev', 'libgl1-mesa-dev',
          'libglu1-mesa-dev', 'mesa-utils']
      - &x11_packages [
          'xorg-dev', 'libdbus-1-dev', 'libx11-dev', 'libxcursor-dev',
          'libxext-dev', 'libxi-dev', 'libxinerama-dev', 'libxrandr-dev',
          'libxss-dev', 'libxt-dev', 'libxv-dev', 'libxxf86vm-dev',
          'libts-dev', 'libudev-dev']

matrix:
  fast_finish: true
  allow_failures:
      - python: "3.4"
      - python: "3.5"
      - python: "3.7"
      - python: "nightly"  # points to 3.7-dev currently (2016-12-28)

# Install system dependencies
before_install:
  # Update System
  - mkdir -p $HOME/.local/envs

  # Install GLFW $GLFW_VERSION
  - wget -O glfw.zip https://github.com/glfw/glfw/releases/download/$GLFW_VERSION/glfw-$GLFW_VERSION.zip
  - unzip glfw.zip
  - cd glfw-$GLFW_VERSION
  - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=$HOME
  - make
  - sudo make install
  - "export GLFW_LIBRARY=${HOME}/lib/libglfw.so"
  - cd ..

  # Install special pypy numpy for pypy compatibility or grab standard
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then travis_retry pip install git+https://bitbucket.org/pypy/numpy.git@pypy-4.0.1; fi

install:
  - pip install -e .[tests]
  - pip install circus tox-travis

# command to run tests
script:
   # Run each separately so we have an idea of what's broken in travis
  # glfw-cffi requires a working X11 display to run any tests
  - circusd circus-startup-xvfb.ini --daemon
  - circusctl list
  - circusctl status xvfb
  - circusctl stats xvfb
  - python -c 'import glfw; assert glfw.init() == glfw.gl.TRUE'
  - echo "travis_fold:start:glxinfo" && glxinfo && echo "travis_fold:end:glxinfo"
  - py.test

after_success:
   - coveralls
